require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anamneses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Anamnese. As you add validations to Anamnese, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Anamnese.create! valid_attributes
      get anamneses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anamnese = Anamnese.create! valid_attributes
      get anamnese_url(anamnese)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anamnese_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      anamnese = Anamnese.create! valid_attributes
      get edit_anamnese_url(anamnese)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Anamnese" do
        expect {
          post anamneses_url, params: { anamnese: valid_attributes }
        }.to change(Anamnese, :count).by(1)
      end

      it "redirects to the created anamnese" do
        post anamneses_url, params: { anamnese: valid_attributes }
        expect(response).to redirect_to(anamnese_url(Anamnese.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Anamnese" do
        expect {
          post anamneses_url, params: { anamnese: invalid_attributes }
        }.to change(Anamnese, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post anamneses_url, params: { anamnese: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anamnese" do
        anamnese = Anamnese.create! valid_attributes
        patch anamnese_url(anamnese), params: { anamnese: new_attributes }
        anamnese.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anamnese" do
        anamnese = Anamnese.create! valid_attributes
        patch anamnese_url(anamnese), params: { anamnese: new_attributes }
        anamnese.reload
        expect(response).to redirect_to(anamnese_url(anamnese))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        anamnese = Anamnese.create! valid_attributes
        patch anamnese_url(anamnese), params: { anamnese: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anamnese" do
      anamnese = Anamnese.create! valid_attributes
      expect {
        delete anamnese_url(anamnese)
      }.to change(Anamnese, :count).by(-1)
    end

    it "redirects to the anamneses list" do
      anamnese = Anamnese.create! valid_attributes
      delete anamnese_url(anamnese)
      expect(response).to redirect_to(anamneses_url)
    end
  end
end
