require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cnpjs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cnpj. As you add validations to Cnpj, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cnpj.create! valid_attributes
      get cnpjs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cnpj = Cnpj.create! valid_attributes
      get cnpj_url(cnpj)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cnpj_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cnpj = Cnpj.create! valid_attributes
      get edit_cnpj_url(cnpj)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cnpj" do
        expect {
          post cnpjs_url, params: { cnpj: valid_attributes }
        }.to change(Cnpj, :count).by(1)
      end

      it "redirects to the created cnpj" do
        post cnpjs_url, params: { cnpj: valid_attributes }
        expect(response).to redirect_to(cnpj_url(Cnpj.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cnpj" do
        expect {
          post cnpjs_url, params: { cnpj: invalid_attributes }
        }.to change(Cnpj, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cnpjs_url, params: { cnpj: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cnpj" do
        cnpj = Cnpj.create! valid_attributes
        patch cnpj_url(cnpj), params: { cnpj: new_attributes }
        cnpj.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cnpj" do
        cnpj = Cnpj.create! valid_attributes
        patch cnpj_url(cnpj), params: { cnpj: new_attributes }
        cnpj.reload
        expect(response).to redirect_to(cnpj_url(cnpj))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cnpj = Cnpj.create! valid_attributes
        patch cnpj_url(cnpj), params: { cnpj: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cnpj" do
      cnpj = Cnpj.create! valid_attributes
      expect {
        delete cnpj_url(cnpj)
      }.to change(Cnpj, :count).by(-1)
    end

    it "redirects to the cnpjs list" do
      cnpj = Cnpj.create! valid_attributes
      delete cnpj_url(cnpj)
      expect(response).to redirect_to(cnpjs_url)
    end
  end
end
