require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cpfs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cpf. As you add validations to Cpf, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cpf.create! valid_attributes
      get cpfs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cpf = Cpf.create! valid_attributes
      get cpf_url(cpf)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cpf_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cpf = Cpf.create! valid_attributes
      get edit_cpf_url(cpf)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cpf" do
        expect {
          post cpfs_url, params: { cpf: valid_attributes }
        }.to change(Cpf, :count).by(1)
      end

      it "redirects to the created cpf" do
        post cpfs_url, params: { cpf: valid_attributes }
        expect(response).to redirect_to(cpf_url(Cpf.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cpf" do
        expect {
          post cpfs_url, params: { cpf: invalid_attributes }
        }.to change(Cpf, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cpfs_url, params: { cpf: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cpf" do
        cpf = Cpf.create! valid_attributes
        patch cpf_url(cpf), params: { cpf: new_attributes }
        cpf.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cpf" do
        cpf = Cpf.create! valid_attributes
        patch cpf_url(cpf), params: { cpf: new_attributes }
        cpf.reload
        expect(response).to redirect_to(cpf_url(cpf))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cpf = Cpf.create! valid_attributes
        patch cpf_url(cpf), params: { cpf: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cpf" do
      cpf = Cpf.create! valid_attributes
      expect {
        delete cpf_url(cpf)
      }.to change(Cpf, :count).by(-1)
    end

    it "redirects to the cpfs list" do
      cpf = Cpf.create! valid_attributes
      delete cpf_url(cpf)
      expect(response).to redirect_to(cpfs_url)
    end
  end
end
