require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/estado_civils", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EstadoCivil. As you add validations to EstadoCivil, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EstadoCivil.create! valid_attributes
      get estado_civils_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      estado_civil = EstadoCivil.create! valid_attributes
      get estado_civil_url(estado_civil)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_estado_civil_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      estado_civil = EstadoCivil.create! valid_attributes
      get edit_estado_civil_url(estado_civil)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EstadoCivil" do
        expect {
          post estado_civils_url, params: { estado_civil: valid_attributes }
        }.to change(EstadoCivil, :count).by(1)
      end

      it "redirects to the created estado_civil" do
        post estado_civils_url, params: { estado_civil: valid_attributes }
        expect(response).to redirect_to(estado_civil_url(EstadoCivil.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EstadoCivil" do
        expect {
          post estado_civils_url, params: { estado_civil: invalid_attributes }
        }.to change(EstadoCivil, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post estado_civils_url, params: { estado_civil: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested estado_civil" do
        estado_civil = EstadoCivil.create! valid_attributes
        patch estado_civil_url(estado_civil), params: { estado_civil: new_attributes }
        estado_civil.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the estado_civil" do
        estado_civil = EstadoCivil.create! valid_attributes
        patch estado_civil_url(estado_civil), params: { estado_civil: new_attributes }
        estado_civil.reload
        expect(response).to redirect_to(estado_civil_url(estado_civil))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        estado_civil = EstadoCivil.create! valid_attributes
        patch estado_civil_url(estado_civil), params: { estado_civil: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested estado_civil" do
      estado_civil = EstadoCivil.create! valid_attributes
      expect {
        delete estado_civil_url(estado_civil)
      }.to change(EstadoCivil, :count).by(-1)
    end

    it "redirects to the estado_civils list" do
      estado_civil = EstadoCivil.create! valid_attributes
      delete estado_civil_url(estado_civil)
      expect(response).to redirect_to(estado_civils_url)
    end
  end
end
