require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/historia_sexual_reprodutivas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HistoriaSexualReprodutiva. As you add validations to HistoriaSexualReprodutiva, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HistoriaSexualReprodutiva.create! valid_attributes
      get historia_sexual_reprodutivas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
      get historia_sexual_reprodutiva_url(historia_sexual_reprodutiva)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_historia_sexual_reprodutiva_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
      get edit_historia_sexual_reprodutiva_url(historia_sexual_reprodutiva)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HistoriaSexualReprodutiva" do
        expect {
          post historia_sexual_reprodutivas_url, params: { historia_sexual_reprodutiva: valid_attributes }
        }.to change(HistoriaSexualReprodutiva, :count).by(1)
      end

      it "redirects to the created historia_sexual_reprodutiva" do
        post historia_sexual_reprodutivas_url, params: { historia_sexual_reprodutiva: valid_attributes }
        expect(response).to redirect_to(historia_sexual_reprodutiva_url(HistoriaSexualReprodutiva.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HistoriaSexualReprodutiva" do
        expect {
          post historia_sexual_reprodutivas_url, params: { historia_sexual_reprodutiva: invalid_attributes }
        }.to change(HistoriaSexualReprodutiva, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post historia_sexual_reprodutivas_url, params: { historia_sexual_reprodutiva: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested historia_sexual_reprodutiva" do
        historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
        patch historia_sexual_reprodutiva_url(historia_sexual_reprodutiva), params: { historia_sexual_reprodutiva: new_attributes }
        historia_sexual_reprodutiva.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the historia_sexual_reprodutiva" do
        historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
        patch historia_sexual_reprodutiva_url(historia_sexual_reprodutiva), params: { historia_sexual_reprodutiva: new_attributes }
        historia_sexual_reprodutiva.reload
        expect(response).to redirect_to(historia_sexual_reprodutiva_url(historia_sexual_reprodutiva))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
        patch historia_sexual_reprodutiva_url(historia_sexual_reprodutiva), params: { historia_sexual_reprodutiva: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested historia_sexual_reprodutiva" do
      historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
      expect {
        delete historia_sexual_reprodutiva_url(historia_sexual_reprodutiva)
      }.to change(HistoriaSexualReprodutiva, :count).by(-1)
    end

    it "redirects to the historia_sexual_reprodutivas list" do
      historia_sexual_reprodutiva = HistoriaSexualReprodutiva.create! valid_attributes
      delete historia_sexual_reprodutiva_url(historia_sexual_reprodutiva)
      expect(response).to redirect_to(historia_sexual_reprodutivas_url)
    end
  end
end
