require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/historia_medica_pregressas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HistoriaMedicaPregressa. As you add validations to HistoriaMedicaPregressa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HistoriaMedicaPregressa.create! valid_attributes
      get historia_medica_pregressas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
      get historia_medica_pregressa_url(historia_medica_pregressa)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_historia_medica_pregressa_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
      get edit_historia_medica_pregressa_url(historia_medica_pregressa)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HistoriaMedicaPregressa" do
        expect {
          post historia_medica_pregressas_url, params: { historia_medica_pregressa: valid_attributes }
        }.to change(HistoriaMedicaPregressa, :count).by(1)
      end

      it "redirects to the created historia_medica_pregressa" do
        post historia_medica_pregressas_url, params: { historia_medica_pregressa: valid_attributes }
        expect(response).to redirect_to(historia_medica_pregressa_url(HistoriaMedicaPregressa.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HistoriaMedicaPregressa" do
        expect {
          post historia_medica_pregressas_url, params: { historia_medica_pregressa: invalid_attributes }
        }.to change(HistoriaMedicaPregressa, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post historia_medica_pregressas_url, params: { historia_medica_pregressa: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested historia_medica_pregressa" do
        historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
        patch historia_medica_pregressa_url(historia_medica_pregressa), params: { historia_medica_pregressa: new_attributes }
        historia_medica_pregressa.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the historia_medica_pregressa" do
        historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
        patch historia_medica_pregressa_url(historia_medica_pregressa), params: { historia_medica_pregressa: new_attributes }
        historia_medica_pregressa.reload
        expect(response).to redirect_to(historia_medica_pregressa_url(historia_medica_pregressa))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
        patch historia_medica_pregressa_url(historia_medica_pregressa), params: { historia_medica_pregressa: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested historia_medica_pregressa" do
      historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
      expect {
        delete historia_medica_pregressa_url(historia_medica_pregressa)
      }.to change(HistoriaMedicaPregressa, :count).by(-1)
    end

    it "redirects to the historia_medica_pregressas list" do
      historia_medica_pregressa = HistoriaMedicaPregressa.create! valid_attributes
      delete historia_medica_pregressa_url(historia_medica_pregressa)
      expect(response).to redirect_to(historia_medica_pregressas_url)
    end
  end
end
