require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/historia_familiars", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HistoriaFamiliar. As you add validations to HistoriaFamiliar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HistoriaFamiliar.create! valid_attributes
      get historia_familiars_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      historia_familiar = HistoriaFamiliar.create! valid_attributes
      get historia_familiar_url(historia_familiar)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_historia_familiar_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      historia_familiar = HistoriaFamiliar.create! valid_attributes
      get edit_historia_familiar_url(historia_familiar)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HistoriaFamiliar" do
        expect {
          post historia_familiars_url, params: { historia_familiar: valid_attributes }
        }.to change(HistoriaFamiliar, :count).by(1)
      end

      it "redirects to the created historia_familiar" do
        post historia_familiars_url, params: { historia_familiar: valid_attributes }
        expect(response).to redirect_to(historia_familiar_url(HistoriaFamiliar.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HistoriaFamiliar" do
        expect {
          post historia_familiars_url, params: { historia_familiar: invalid_attributes }
        }.to change(HistoriaFamiliar, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post historia_familiars_url, params: { historia_familiar: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested historia_familiar" do
        historia_familiar = HistoriaFamiliar.create! valid_attributes
        patch historia_familiar_url(historia_familiar), params: { historia_familiar: new_attributes }
        historia_familiar.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the historia_familiar" do
        historia_familiar = HistoriaFamiliar.create! valid_attributes
        patch historia_familiar_url(historia_familiar), params: { historia_familiar: new_attributes }
        historia_familiar.reload
        expect(response).to redirect_to(historia_familiar_url(historia_familiar))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        historia_familiar = HistoriaFamiliar.create! valid_attributes
        patch historia_familiar_url(historia_familiar), params: { historia_familiar: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested historia_familiar" do
      historia_familiar = HistoriaFamiliar.create! valid_attributes
      expect {
        delete historia_familiar_url(historia_familiar)
      }.to change(HistoriaFamiliar, :count).by(-1)
    end

    it "redirects to the historia_familiars list" do
      historia_familiar = HistoriaFamiliar.create! valid_attributes
      delete historia_familiar_url(historia_familiar)
      expect(response).to redirect_to(historia_familiars_url)
    end
  end
end
