require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/historia_psicologica_psiquiatricas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HistoriaPsicologicaPsiquiatrica. As you add validations to HistoriaPsicologicaPsiquiatrica, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HistoriaPsicologicaPsiquiatrica.create! valid_attributes
      get historia_psicologica_psiquiatricas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
      get historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_historia_psicologica_psiquiatrica_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
      get edit_historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HistoriaPsicologicaPsiquiatrica" do
        expect {
          post historia_psicologica_psiquiatricas_url, params: { historia_psicologica_psiquiatrica: valid_attributes }
        }.to change(HistoriaPsicologicaPsiquiatrica, :count).by(1)
      end

      it "redirects to the created historia_psicologica_psiquiatrica" do
        post historia_psicologica_psiquiatricas_url, params: { historia_psicologica_psiquiatrica: valid_attributes }
        expect(response).to redirect_to(historia_psicologica_psiquiatrica_url(HistoriaPsicologicaPsiquiatrica.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HistoriaPsicologicaPsiquiatrica" do
        expect {
          post historia_psicologica_psiquiatricas_url, params: { historia_psicologica_psiquiatrica: invalid_attributes }
        }.to change(HistoriaPsicologicaPsiquiatrica, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post historia_psicologica_psiquiatricas_url, params: { historia_psicologica_psiquiatrica: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested historia_psicologica_psiquiatrica" do
        historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
        patch historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica), params: { historia_psicologica_psiquiatrica: new_attributes }
        historia_psicologica_psiquiatrica.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the historia_psicologica_psiquiatrica" do
        historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
        patch historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica), params: { historia_psicologica_psiquiatrica: new_attributes }
        historia_psicologica_psiquiatrica.reload
        expect(response).to redirect_to(historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
        patch historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica), params: { historia_psicologica_psiquiatrica: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested historia_psicologica_psiquiatrica" do
      historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
      expect {
        delete historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica)
      }.to change(HistoriaPsicologicaPsiquiatrica, :count).by(-1)
    end

    it "redirects to the historia_psicologica_psiquiatricas list" do
      historia_psicologica_psiquiatrica = HistoriaPsicologicaPsiquiatrica.create! valid_attributes
      delete historia_psicologica_psiquiatrica_url(historia_psicologica_psiquiatrica)
      expect(response).to redirect_to(historia_psicologica_psiquiatricas_url)
    end
  end
end
