require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/notificacaos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Notificacao. As you add validations to Notificacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Notificacao.create! valid_attributes
      get notificacaos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      notificacao = Notificacao.create! valid_attributes
      get notificacao_url(notificacao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_notificacao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      notificacao = Notificacao.create! valid_attributes
      get edit_notificacao_url(notificacao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Notificacao" do
        expect {
          post notificacaos_url, params: { notificacao: valid_attributes }
        }.to change(Notificacao, :count).by(1)
      end

      it "redirects to the created notificacao" do
        post notificacaos_url, params: { notificacao: valid_attributes }
        expect(response).to redirect_to(notificacao_url(Notificacao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Notificacao" do
        expect {
          post notificacaos_url, params: { notificacao: invalid_attributes }
        }.to change(Notificacao, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post notificacaos_url, params: { notificacao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested notificacao" do
        notificacao = Notificacao.create! valid_attributes
        patch notificacao_url(notificacao), params: { notificacao: new_attributes }
        notificacao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the notificacao" do
        notificacao = Notificacao.create! valid_attributes
        patch notificacao_url(notificacao), params: { notificacao: new_attributes }
        notificacao.reload
        expect(response).to redirect_to(notificacao_url(notificacao))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        notificacao = Notificacao.create! valid_attributes
        patch notificacao_url(notificacao), params: { notificacao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested notificacao" do
      notificacao = Notificacao.create! valid_attributes
      expect {
        delete notificacao_url(notificacao)
      }.to change(Notificacao, :count).by(-1)
    end

    it "redirects to the notificacaos list" do
      notificacao = Notificacao.create! valid_attributes
      delete notificacao_url(notificacao)
      expect(response).to redirect_to(notificacaos_url)
    end
  end
end
