require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/profissaos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Profissao. As you add validations to Profissao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Profissao.create! valid_attributes
      get profissaos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      profissao = Profissao.create! valid_attributes
      get profissao_url(profissao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_profissao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      profissao = Profissao.create! valid_attributes
      get edit_profissao_url(profissao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Profissao" do
        expect {
          post profissaos_url, params: { profissao: valid_attributes }
        }.to change(Profissao, :count).by(1)
      end

      it "redirects to the created profissao" do
        post profissaos_url, params: { profissao: valid_attributes }
        expect(response).to redirect_to(profissao_url(Profissao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Profissao" do
        expect {
          post profissaos_url, params: { profissao: invalid_attributes }
        }.to change(Profissao, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post profissaos_url, params: { profissao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested profissao" do
        profissao = Profissao.create! valid_attributes
        patch profissao_url(profissao), params: { profissao: new_attributes }
        profissao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the profissao" do
        profissao = Profissao.create! valid_attributes
        patch profissao_url(profissao), params: { profissao: new_attributes }
        profissao.reload
        expect(response).to redirect_to(profissao_url(profissao))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        profissao = Profissao.create! valid_attributes
        patch profissao_url(profissao), params: { profissao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested profissao" do
      profissao = Profissao.create! valid_attributes
      expect {
        delete profissao_url(profissao)
      }.to change(Profissao, :count).by(-1)
    end

    it "redirects to the profissaos list" do
      profissao = Profissao.create! valid_attributes
      delete profissao_url(profissao)
      expect(response).to redirect_to(profissaos_url)
    end
  end
end
