require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/revisao_sistemas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RevisaoSistema. As you add validations to RevisaoSistema, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RevisaoSistema.create! valid_attributes
      get revisao_sistemas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      revisao_sistema = RevisaoSistema.create! valid_attributes
      get revisao_sistema_url(revisao_sistema)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_revisao_sistema_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      revisao_sistema = RevisaoSistema.create! valid_attributes
      get edit_revisao_sistema_url(revisao_sistema)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RevisaoSistema" do
        expect {
          post revisao_sistemas_url, params: { revisao_sistema: valid_attributes }
        }.to change(RevisaoSistema, :count).by(1)
      end

      it "redirects to the created revisao_sistema" do
        post revisao_sistemas_url, params: { revisao_sistema: valid_attributes }
        expect(response).to redirect_to(revisao_sistema_url(RevisaoSistema.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RevisaoSistema" do
        expect {
          post revisao_sistemas_url, params: { revisao_sistema: invalid_attributes }
        }.to change(RevisaoSistema, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post revisao_sistemas_url, params: { revisao_sistema: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested revisao_sistema" do
        revisao_sistema = RevisaoSistema.create! valid_attributes
        patch revisao_sistema_url(revisao_sistema), params: { revisao_sistema: new_attributes }
        revisao_sistema.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the revisao_sistema" do
        revisao_sistema = RevisaoSistema.create! valid_attributes
        patch revisao_sistema_url(revisao_sistema), params: { revisao_sistema: new_attributes }
        revisao_sistema.reload
        expect(response).to redirect_to(revisao_sistema_url(revisao_sistema))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        revisao_sistema = RevisaoSistema.create! valid_attributes
        patch revisao_sistema_url(revisao_sistema), params: { revisao_sistema: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested revisao_sistema" do
      revisao_sistema = RevisaoSistema.create! valid_attributes
      expect {
        delete revisao_sistema_url(revisao_sistema)
      }.to change(RevisaoSistema, :count).by(-1)
    end

    it "redirects to the revisao_sistemas list" do
      revisao_sistema = RevisaoSistema.create! valid_attributes
      delete revisao_sistema_url(revisao_sistema)
      expect(response).to redirect_to(revisao_sistemas_url)
    end
  end
end
