require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/revisao_habitos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RevisaoHabito. As you add validations to RevisaoHabito, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RevisaoHabito.create! valid_attributes
      get revisao_habitos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      revisao_habito = RevisaoHabito.create! valid_attributes
      get revisao_habito_url(revisao_habito)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_revisao_habito_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      revisao_habito = RevisaoHabito.create! valid_attributes
      get edit_revisao_habito_url(revisao_habito)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RevisaoHabito" do
        expect {
          post revisao_habitos_url, params: { revisao_habito: valid_attributes }
        }.to change(RevisaoHabito, :count).by(1)
      end

      it "redirects to the created revisao_habito" do
        post revisao_habitos_url, params: { revisao_habito: valid_attributes }
        expect(response).to redirect_to(revisao_habito_url(RevisaoHabito.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RevisaoHabito" do
        expect {
          post revisao_habitos_url, params: { revisao_habito: invalid_attributes }
        }.to change(RevisaoHabito, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post revisao_habitos_url, params: { revisao_habito: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested revisao_habito" do
        revisao_habito = RevisaoHabito.create! valid_attributes
        patch revisao_habito_url(revisao_habito), params: { revisao_habito: new_attributes }
        revisao_habito.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the revisao_habito" do
        revisao_habito = RevisaoHabito.create! valid_attributes
        patch revisao_habito_url(revisao_habito), params: { revisao_habito: new_attributes }
        revisao_habito.reload
        expect(response).to redirect_to(revisao_habito_url(revisao_habito))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        revisao_habito = RevisaoHabito.create! valid_attributes
        patch revisao_habito_url(revisao_habito), params: { revisao_habito: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested revisao_habito" do
      revisao_habito = RevisaoHabito.create! valid_attributes
      expect {
        delete revisao_habito_url(revisao_habito)
      }.to change(RevisaoHabito, :count).by(-1)
    end

    it "redirects to the revisao_habitos list" do
      revisao_habito = RevisaoHabito.create! valid_attributes
      delete revisao_habito_url(revisao_habito)
      expect(response).to redirect_to(revisao_habitos_url)
    end
  end
end
